import React from "react";
import Goo from "gooey-react";

function GooeyBG() {
  function generateRandomCY() {
    const rand = Math.random() * 15;

    return `${rand + 180}vh`;
  }

  const color1 = "#ffbe0b";
  const color2 = "#ff006e";

  return (
    <Goo width="100vw" height="100vh" className="background-goo">
      <svg
        className="goo-container"
        xmlns="http://www.w3.org/2000/svg"
        version="1.1"
      >
        {/* verticals */}
        <circle
          cx="12%"
          cy={generateRandomCY()}
          fill={color1}
          r="11vw"
          className="vert8"
        />
        <circle
          cx="85%"
          cy={generateRandomCY()}
          fill={color1}
          r="13vw"
          className="vert8"
        />
        <circle
          cx="29%"
          cy={generateRandomCY()}
          fill={color1}
          r="12vw"
          className="vert8"
        />
        <circle
          cx="87%"
          cy={generateRandomCY()}
          fill={color1}
          r="27vw"
          className="vert12"
        />
        <circle
          cx="4%"
          cy={generateRandomCY()}
          fill={color1}
          r="14vw"
          className="vert8"
        />
        <circle
          cx="15%"
          cy={generateRandomCY()}
          fill={color1}
          r="25vw"
          className="vert12"
        />
        <circle
          cx="60%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="vert10"
        />
        <circle
          cx="20%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="vert10"
        />
        <circle
          cx="66%"
          cy={generateRandomCY()}
          fill={color2}
          r="23vw"
          className="vert12"
        />
        {/* <circle
          cx="49%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="vert8"
        />
        <circle
          cx="1%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="vert10"
        />
        <circle
          cx="43%"
          cy={generateRandomCY()}
          fill={color2}
          r="25vw"
          className="vert12"
        />
        <circle
          cx="78%"
          cy={generateRandomCY()}
          fill={color2}
          r="25vw"
          className="vert12"
        /> */}
        {/* diagonals right*/}
        <circle
          cx="60%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="diagR8"
        />
        <circle
          cx="66%"
          cy={generateRandomCY()}
          fill={color2}
          r="13vw"
          className="diagR10"
        />
        <circle
          cx="49%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagR12"
        />{" "}
        /
        <circle
          cx="1%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagR8"
        />
        <circle
          cx="43%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagR12"
        />
        <circle
          cx="78%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagR10"
        />
        <circle
          cx="85%"
          cy={generateRandomCY()}
          fill={color1}
          r="19vw"
          className="diagR10"
        />
        {/* <circle
          cx="29%"
          cy={generateRandomCY()}
          fill={color1}
          r="11vw"
          className="diagR8"
        />
        <circle
          cx="87%"
          cy={generateRandomCY()}
          fill={color1}
          r="17vw"
          className="diagR12"
        />
        <circle
          cx="12%"
          cy={generateRandomCY()}
          fill={color1}
          r="11vw"
          className="diagR10"
        />
        <circle
          cx="4%"
          cy={generateRandomCY()}
          fill={color1}
          r="14vw"
          className="diagR10"
        />
        <circle
          cx="15%"
          cy={generateRandomCY()}
          fill={color1}
          r="15vw"
          className="diagR12"
        />
        <circle
          cx="20%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="diagR8"
        /> */}
        {/* diagonal left */}
        <circle
          cx="1%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagL8"
        />
        <circle
          cx="43%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagL10"
        />
        <circle
          cx="78%"
          cy={generateRandomCY()}
          fill={color2}
          r="11vw"
          className="diagL8"
        />
        <circle
          cx="85%"
          cy={generateRandomCY()}
          fill={color1}
          r="19vw"
          className="diagL10"
        />
        <circle
          cx="29%"
          cy={generateRandomCY()}
          fill={color1}
          r="11vw"
          className="diagL8"
        />
        <circle
          cx="87%"
          cy={generateRandomCY()}
          fill={color1}
          r="17vw"
          className="diagL8"
        />
        {/* <circle
          cx="12%"
          cy={generateRandomCY()}
          fill={color1}
          r="11vw"
          className="diagL8"
        />
        <circle
          cx="4%"
          cy={generateRandomCY()}
          fill={color1}
          r="14vw"
          className="diagL8"
        />
        <circle
          cx="15%"
          cy={generateRandomCY()}
          fill={color1}
          r="15vw"
          className="diagL8"
        />
        <circle
          cx="20%"
          cy={generateRandomCY()}
          fill={color2}
          r="15vw"
          className="diagL8"
        />
           */}
      </svg>
    </Goo>
  );
}

export default GooeyBG;
